import source from '../../config/print-shop.json';
import { SHOP_COLOURS, type ShopColour } from './print-shop';

/**
 * Merchandising data for /sklep, keyed by design id (`fapNNN`).
 *
 * Kept as static JSON — like config/print-catalog-curation.json — rather than
 * a PrintDesign field: under CATALOG_SOURCE=db the catalog mapper rebuilds
 * designs field-by-field from DB rows, so a registry-only field would be
 * silently dropped.
 *
 *  - `designs[id].colours`: colour families for the shop filter. Generated by
 *    `npm run print-assets:facets`; `reviewed: true` marks a human-checked
 *    entry that the script never overwrites (without --force).
 *  - `featured`: ids pinned first in the default order and badged
 *    "Artist's pick". Hand-maintained.
 *  - `newCount`: how many of the highest-numbered designs carry the "New" badge.
 */
export interface PrintShopDesignEntry {
  colours: ShopColour[];
  reviewed: boolean;
}

export interface PrintShopConfig {
  schemaVersion: 1;
  featured: string[];
  newCount: number;
  designs: Record<string, PrintShopDesignEntry>;
}

function fail(message: string): never {
  throw new Error(`Invalid print shop config: ${message}`);
}

/** Throws on a malformed config; `knownIds` (when given) also rejects ids outside the registry. */
export function validatePrintShopConfig(input: unknown, knownIds?: readonly string[]): PrintShopConfig {
  const cfg = input as Partial<PrintShopConfig> | null;
  if (!cfg || typeof cfg !== 'object') fail('must be an object');
  if (cfg.schemaVersion !== 1) fail(`unsupported schemaVersion ${String(cfg.schemaVersion)}`);
  if (!Array.isArray(cfg.featured) || cfg.featured.some((id) => typeof id !== 'string')) fail('featured must be an array of ids');
  if (new Set(cfg.featured).size !== cfg.featured.length) fail('featured contains duplicate ids');
  if (!Number.isInteger(cfg.newCount) || (cfg.newCount as number) < 0 || (cfg.newCount as number) > 60) fail('newCount must be an integer 0–60');
  if (!cfg.designs || typeof cfg.designs !== 'object' || Array.isArray(cfg.designs)) fail('designs must be an object keyed by id');

  const known = knownIds ? new Set(knownIds) : undefined;
  for (const [id, entry] of Object.entries(cfg.designs)) {
    if (!/^fap\d{3,}$/.test(id)) fail(`bad design id "${id}"`);
    if (known && !known.has(id)) fail(`unknown design id "${id}"`);
    if (!entry || !Array.isArray(entry.colours) || typeof entry.reviewed !== 'boolean') fail(`${id} needs { colours: [], reviewed: boolean }`);
    if (new Set(entry.colours).size !== entry.colours.length) fail(`${id} has duplicate colours`);
    for (const c of entry.colours) {
      if (!(SHOP_COLOURS as readonly string[]).includes(c)) fail(`${id} has unknown colour "${String(c)}"`);
    }
  }
  if (known) {
    for (const id of cfg.featured) if (!known.has(id)) fail(`featured id "${id}" is not a known design`);
  }
  return cfg as PrintShopConfig;
}

export const PRINT_SHOP_CONFIG: PrintShopConfig = validatePrintShopConfig(source);

/** Colour families of a design; [] when it has no entry (it then never matches a colour filter). */
export function shopColoursFor(id: string, config: PrintShopConfig = PRINT_SHOP_CONFIG): ShopColour[] {
  return config.designs[id]?.colours ?? [];
}
