-- CMS API (S1) — product drafts, publish/availability RPCs, idempotency ledger.
-- -----------------------------------------------------------------------------
-- Additive only: one new table (product_drafts) backing per-product draft/
-- revision history (mirrors cms_document_versions, but keyed by product_id
-- with a single payload per revision instead of per-locale versioning),
-- one new nullable column on products (published_revision, composite-FK'd to
-- product_drafts) and on catalog_audit_log (revision), one new table for
-- Idempotency-Key handling, and three RPCs mirroring the existing
-- publish_cms_version / update_product_status_guarded / publish_print_asset_revision
-- conventions (one-transaction locks, search_path pinned, service_role only).
--
-- Same RLS posture as every sibling table: enabled, no policies.

-- 1. product_drafts ───────────────────────────────────────────────────────────
create table product_drafts (
  id          uuid primary key default gen_random_uuid(),
  product_id  text not null references products(id) on delete cascade,
  revision    integer not null,
  payload     jsonb not null,
  created_by  text,
  created_at  timestamptz not null default now(),
  unique (product_id, revision)
);

alter table product_drafts enable row level security;

create index product_drafts_product_idx on product_drafts (product_id, revision desc);

-- 2. products.published_revision ──────────────────────────────────────────────
alter table products add column published_revision integer;

alter table products
  add constraint products_published_revision_fk
  foreign key (id, published_revision) references product_drafts (product_id, revision);

-- 3. catalog_audit_log.revision ───────────────────────────────────────────────
alter table catalog_audit_log add column revision integer;

-- 4. cms_api_idempotency_keys ──────────────────────────────────────────────────
-- Leased-CAS ledger, same shape as webhook_events (src/lib/webhook.ts):
-- 'processing' with a fresh processing_started_at means "in flight, ask the
-- caller to retry with 409"; a stale lease may be reclaimed; 'done' replays
-- the stored response verbatim; a request_hash mismatch on a live key is a
-- client bug (same key reused for a different payload).
create table cms_api_idempotency_keys (
  id                    uuid primary key default gen_random_uuid(),
  operation             text not null,
  idempotency_key       text not null,
  status                text not null default 'processing' check (status in ('processing', 'done', 'failed')),
  request_hash          text,
  response_status       integer,
  response_body         jsonb,
  processing_started_at timestamptz not null default now(),
  completed_at          timestamptz,
  created_at            timestamptz not null default now(),
  unique (operation, idempotency_key)
);

alter table cms_api_idempotency_keys enable row level security;

-- 5. create_product_with_draft ────────────────────────────────────────────────
-- Atomically creates the products row (status='draft') and its first
-- product_drafts revision. p_id is generated by the caller (prd_<10 hex>);
-- a collision (extremely unlikely) surfaces as a 23505 unique_violation on
-- products_pkey for the caller to catch and retry with a new id.
create or replace function create_product_with_draft(
  p_id            text,
  p_type          text,
  p_category_slug text,
  p_num           text,
  p_payload       jsonb,
  p_actor_email   text
) returns product_drafts
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_row product_drafts%rowtype;
begin
  if p_type not in ('ceramic', 'print') then
    raise 'invalid_type';
  end if;

  insert into products (id, type, category_slug, num, status)
  values (p_id, p_type, p_category_slug, p_num, 'draft');

  insert into product_drafts (product_id, revision, payload, created_by)
  values (p_id, 1, p_payload, p_actor_email)
  returning * into v_row;

  insert into catalog_audit_log (product_id, actor_email, action, before, after, revision)
  values (p_id, p_actor_email, 'draft_saved', null, p_payload, 1);

  return v_row;
end;
$$;

revoke all on function create_product_with_draft(text, text, text, text, jsonb, text) from public, anon, authenticated;
grant execute on function create_product_with_draft(text, text, text, text, jsonb, text) to service_role;

-- 6. save_product_draft ────────────────────────────────────────────────────────
create or replace function save_product_draft(
  p_product_id        text,
  p_expected_revision integer,
  p_payload           jsonb,
  p_actor_email       text
) returns product_drafts
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_current_revision integer;
  v_new_revision      integer;
  v_row               product_drafts%rowtype;
  v_previous          jsonb;
begin
  perform 1 from products p where p.id = p_product_id for update;
  if not found then
    raise 'product_not_found';
  end if;

  select coalesce(max(pd.revision), 0)
    into v_current_revision
    from product_drafts pd
   where pd.product_id = p_product_id;

  if v_current_revision <> p_expected_revision then
    raise 'revision_conflict' using detail = format('currentRevision=%s', v_current_revision);
  end if;

  select pd.payload
    into v_previous
    from product_drafts pd
   where pd.product_id = p_product_id
   order by pd.revision desc
   limit 1;

  v_new_revision := v_current_revision + 1;

  insert into product_drafts (product_id, revision, payload, created_by)
  values (p_product_id, v_new_revision, p_payload, p_actor_email)
  returning * into v_row;

  insert into catalog_audit_log (product_id, actor_email, action, before, after, revision)
  values (p_product_id, p_actor_email, 'draft_saved', v_previous, p_payload, v_new_revision);

  return v_row;
end;
$$;

revoke all on function save_product_draft(text, integer, jsonb, text) from public, anon, authenticated;
grant execute on function save_product_draft(text, integer, jsonb, text) to service_role;

-- 7. publish_product_revision ──────────────────────────────────────────────────
-- p_variants (print only): [{variant_key, sku, print_area_width_px, print_area_height_px}]
-- p_media: [{url, alt, position, is_primary}] or null to leave product_media untouched
-- p_structural (ceramic only): {category_slug, num, measure, price_pln, price_eur, price_gbp, drop_id, seo_title, seo_description}
-- Every column reference is table-aliased (RETURNS TABLE-style ambiguity hazard
-- publish_cms_version and publish_print_asset_revision both call out) even
-- though this function returns jsonb, to stay consistent with that convention.
create or replace function publish_product_revision(
  p_product_id        text,
  p_expected_revision integer,
  p_action            text,
  p_actor_email       text,
  p_variants          jsonb default null,
  p_media             jsonb default null,
  p_structural        jsonb default null
) returns jsonb
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_current_revision integer;
  v_product          products%rowtype;
  v_missing          text[];
  v_before           jsonb;
  v_after            jsonb;
begin
  if p_action not in ('publish', 'hide', 'archive') then
    raise 'invalid_action';
  end if;

  select * into v_product from products p where p.id = p_product_id for update;
  if not found then
    raise 'product_not_found';
  end if;

  select coalesce(max(pd.revision), 0)
    into v_current_revision
    from product_drafts pd
   where pd.product_id = p_product_id;

  if v_current_revision <> p_expected_revision then
    raise 'revision_conflict' using detail = format('currentRevision=%s', v_current_revision);
  end if;

  v_before := to_jsonb(v_product);

  if p_action = 'publish' then
    if v_product.type = 'print' then
      if p_variants is null then
        raise 'variants_required';
      end if;

      delete from product_variants pv where pv.product_id = p_product_id;

      insert into product_variants (
        product_id, variant_key, sku, is_default, active, position,
        track_inventory, stock_quantity, allow_backorder,
        print_area_width_px, print_area_height_px
      )
      select
        p_product_id,
        j.obj->>'variant_key',
        j.obj->>'sku',
        false,
        true,
        (j.idx - 1)::integer,
        false, 0, true,
        (j.obj->>'print_area_width_px')::integer,
        (j.obj->>'print_area_height_px')::integer
      from jsonb_array_elements(p_variants) with ordinality as j(obj, idx);

      select array_agg(m)
        into v_missing
        from print_asset_readiness_missing(array[p_product_id]) as m;

      if coalesce(array_length(v_missing, 1), 0) > 0 then
        raise 'print_assets_incomplete' using detail = format('missing=%L', v_missing);
      end if;
    else
      if p_structural is null then
        raise 'structural_required';
      end if;

      update products p set
        category_slug   = coalesce(p_structural->>'category_slug', p.category_slug),
        num             = coalesce(p_structural->>'num', p.num),
        measure         = coalesce(p_structural->>'measure', p.measure),
        price_pln       = (p_structural->>'price_pln')::integer,
        price_eur       = (p_structural->>'price_eur')::integer,
        price_gbp       = (p_structural->>'price_gbp')::integer,
        drop_id         = p_structural->>'drop_id',
        seo_title       = p_structural->>'seo_title',
        seo_description = p_structural->>'seo_description'
      where p.id = p_product_id;

      insert into product_variants (product_id, variant_key, is_default, active)
      values (p_product_id, 'default', true, true)
      on conflict (product_id, variant_key) do nothing;

      insert into piece_state (product_id, status)
      values (p_product_id, 'available')
      on conflict (product_id) do nothing;
    end if;

    if p_media is not null then
      delete from product_media pm where pm.product_id = p_product_id;

      insert into product_media (product_id, url, alt, position, is_primary)
      select p_product_id, j.obj->>'url', j.obj->>'alt', (j.obj->>'position')::integer, (j.obj->>'is_primary')::boolean
        from jsonb_array_elements(p_media) with ordinality as j(obj, idx);
    end if;

    update products p set
      status              = 'active',
      published_revision  = p_expected_revision,
      published_at        = coalesce(p.published_at, now()),
      updated_at          = now()
    where p.id = p_product_id;
  else
    update products p set
      status     = case p_action when 'hide' then 'hidden' else 'archived' end,
      updated_at = now()
    where p.id = p_product_id;
  end if;

  select * into v_product from products p where p.id = p_product_id;
  v_after := to_jsonb(v_product);

  insert into catalog_audit_log (product_id, actor_email, action, before, after, revision)
  values (
    p_product_id,
    p_actor_email,
    case p_action when 'publish' then 'status:active' when 'hide' then 'status:hidden' else 'status:archived' end,
    v_before,
    v_after,
    p_expected_revision
  );

  return jsonb_build_object('ok', true, 'product', v_after);
end;
$$;

revoke all on function publish_product_revision(text, integer, text, text, jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function publish_product_revision(text, integer, text, text, jsonb, jsonb, jsonb) to service_role;

-- 8. set_piece_availability_guarded ────────────────────────────────────────────
create or replace function set_piece_availability_guarded(
  p_product_id   text,
  p_availability text,
  p_showroom     boolean,
  p_actor_email  text
) returns jsonb
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_row    piece_state%rowtype;
  v_before jsonb;
  v_after  jsonb;
begin
  if p_availability not in ('available', 'sold') then
    raise 'invalid_availability';
  end if;

  insert into piece_state (product_id, status)
  values (p_product_id, 'available')
  on conflict (product_id) do nothing;

  select * into v_row from piece_state ps where ps.product_id = p_product_id for update;
  if not found then
    raise 'piece_not_found';
  end if;

  if v_row.status = 'reserved' and v_row.reserved_until is not null and v_row.reserved_until > now() then
    raise 'reservation_active' using detail = 'held_for_checkout';
  end if;

  if p_availability = 'available' and v_row.status = 'sold' and v_row.order_id is not null then
    raise 'reservation_active' using detail = 'sold_online';
  end if;

  v_before := to_jsonb(v_row);

  update piece_state ps set
    status               = p_availability,
    showroom             = p_showroom,
    showroom_entered_at  = case when p_showroom then coalesce(ps.showroom_entered_at, now()) else null end,
    showroom_note        = case when p_showroom then ps.showroom_note else null end
  where ps.product_id = p_product_id
  returning * into v_row;

  v_after := to_jsonb(v_row);

  insert into catalog_audit_log (product_id, actor_email, action, before, after)
  values (p_product_id, p_actor_email, 'availability_changed', v_before, v_after);

  return jsonb_build_object('ok', true, 'piece', v_after);
end;
$$;

revoke all on function set_piece_availability_guarded(text, text, boolean, text) from public, anon, authenticated;
grant execute on function set_piece_availability_guarded(text, text, boolean, text) to service_role;

-- ============================================================
-- Rollback (manual):
--   drop function if exists set_piece_availability_guarded(text, text, boolean, text);
--   drop function if exists publish_product_revision(text, integer, text, text, jsonb, jsonb, jsonb);
--   drop function if exists save_product_draft(text, integer, jsonb, text);
--   drop function if exists create_product_with_draft(text, text, text, text, jsonb, text);
--   drop table if exists cms_api_idempotency_keys;
--   alter table catalog_audit_log drop column if exists revision;
--   alter table products drop constraint if exists products_published_revision_fk;
--   alter table products drop column if exists published_revision;
--   drop table if exists product_drafts;
-- ============================================================
